### ISSUE TITLE
Maintenance - Switch to pyproject.toml

### ISSUE THREAD

**Issue by jomey** [M3Works/insitupy#21]
Tried to quickly update the testing CI to these versions:
```
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.XX'
    cache: 'pip'
```

But they require a pyproject.toml or requirements.txt

Vote to switch to a TOML file and also use `hatchling` for building.
